### ISSUE TITLE
Set up the integration of the code coverage service

### ISSUE THREAD

**Issue by rsp9u** [side-runner-py/side-runner-py#11]
Candidates:
* Codecov
* COVERALLS
* Code Climate

@yaamai 
I think Codecov would be better.
Could you tell me your recommendation of the coverage service?

**Comment by yaamai** [comment]
I am not very familiar code-covarage SaaS
But I see some OSS repository in use codecov.

**Comment by rsp9u** [comment]
Thanks for merging.
