### ISSUE TITLE
Environment variables' name sould be with Prefix

### ISSUE THREAD

**Issue by rsp9u** [side-runner-py/side-runner-py#19]
* I'd like to make prefix `SIDE`
* Proxy settings sould be without Prefix

**Comment by rsp9u** [comment]
Uh.. `SIDE_SIDE_FILE` is not cool.

So, is `SRP` better?

**Comment by yaamai** [comment]
How about "SIDE_TEST_FILE"?

**Comment by rsp9u** [comment]
Well, I agree.
