### ISSUE TITLE
Support to pass Desired Capabilities from command line

### ISSUE THREAD

**Issue by qb-nimish** [side-runner-py/side-runner-py#54]
In order to allow run test in different browsers should externalise the Desired capabilities as in case of https://www.selenium.dev/selenium-ide/docs/en/introduction/command-line-runner

**Comment by qb-nimish** [comment]
As per code https://github.com/side-runner-py/side-runner-py/blob/master/side_runner_py/init.py#L7 it looks like tests always run using chrome

**Comment by rsp9u** [comment]
@qb-nimish Thank you for your proposal! I implmented it on #55.

usage:
```
side-runner-py -c browserName=firefox version="72.0" platform=ANY
```
