### ISSUE TITLE
Use driver.quit in place of driver.close in order to stop the browser window completely

### ISSUE THREAD

**Issue by qb-nimish** [side-runner-py/side-runner-py#56]
https://github.com/side-runner-py/side-runner-py/blob/973952f920483a9ad7ba0cc62f2a6dea025080d6/side_runner_py/main.py#L110

They do a similar thing but not exactly the same. driver.quit() is used to exit the browser, end the session, tabs, pop-ups etc.

But the when you driver.close(), only the window that has focus is closed. It is better to use driver.close() when you are dealing with multiple tabs or windows.

If we are not closing the window there are some issues happening when trying video recording option with this.

Thanks.

**Comment by rsp9u** [comment]
@qb-nimish 

It looks like `driver.quit()` is NOT used in this repository.
```
$ git clone https://github.com/side-runner-py/side-runner-py.git
$ cd side-runner-py
$ ag driver.quit
$ ag quit
$
```

Your proposal should be `Use driver.quit` not `Use driver.close`, shouldn't it?

**Comment by qb-nimish** [comment]
@rsp9u True. I put in the reverse way. Sorry for the confusion.

**Comment by qb-nimish** [comment]
@rsp9u Hope you will accommodate this in some of your fix.

**Comment by rsp9u** [comment]
@qb-nimish
I don't have the desktop development environment, so I can't perform graphical testing.
Therefore I'm not be able to confirm the side-effect of this change completely.

For the time being, I implemented it as an option like `--close-method=quit` at #65.
Please let me know if there are any problems.

**Comment by qb-nimish** [comment]
@rsp9u Looks good.
